=== Preview rendering

Here the concepts about rendering the Asciidoc files is described and how problems are
handled.

Why is this preview rendering so problematic?
Here a sum up:

- some browsers have/had issues with SAME origin policy (even when file system is used)
- generated image parts have other locations (e.g. asciidoctor diagram)
- base dir handling per editor file
- imageDir attribute settings vs. relative pathes

==== Generated files problem

Unfortunately the generated diagrams do appear inside original sources

So it is necessary to set attribute `imagesoutdir` .

But the location must be the same as
the normal images directory, because asciidoc
just only accept one imagesdir...

So this must be calculated to real
target image directory in temp folder

===== Project folders
The project id is inside the project folder name. 
So we can use this flat way, even when two project names (in different workspaces)
are rendered.

===== Editor files
To have the possiblity to change output behaviour a hidden editor file is used which
includes the origin asciidoc file from eclipse project structure.

This solves also the base dir problematic (the hidden file location is the base dir)

To handle long path problem the hidden editor files we use a prefix from `UniqueAsciidoctorEditorId`
which contains a SHA256 of the file location.

So we can use these files flat inside project, even when filenames are same

===== Images 
There are different kind of images:
- images from project
- generated images by `asciidoctor-diagram`

[IMPORTANT]
====
Unfortunately asciidoctor-diagram output directory does not correlate 100% with imagesdir! 

For more details look at:
https://github.com/asciidoctor/asciidoctor-diagram/issues/110
https://github.com/asciidoctor/asciidoctor-diagram/issues/110#issuecomment-699510148
====

This is solved by modifying/altering the HTML files generated by Asciidoc and
replace unexisting image file locations with the absolute pathes diagram output
folder content.

==== Same origin problems with images (no longer a problem)

To avoid same origin problems with relative paths we use for preview rendering always absolute 
pahtes. This works well with 

Linux
- Chrome Version 90.0.4430.93 (Official Build) for Linux Mint (64-bit)
- Firefox 88.0.1 (64-bit Linux Mint)

Windows 10
- Chrome
- Firefox

Formerly to avoid same origin problems the `<img src="./..">` parts inside generated HTML are inspected
and the necessary images were copied.

But this is no longer necessary when using the aboslute paths.
